### PR TITLE
Changes for two column resume format.

### PR DESCRIPTION
**Pull request by tiendan**
Style changes for two column resume. Added the new examples in the examples/ folder (.tex, .pdf and .png files). Took the liberty to reduce the two column example to one page (by commenting out extracurricular and committees sections) to demonstrate a compact version.

### CODE REVIEW

**Comment by timozattol** [comment]
Nice! I'd love to be able to use that :) Waiting for PR to be accepted. 

Adding for example a "Language" section on the two-column version seems nicer, it would take a lot of space on the one-column version.

**Comment by timozattol** [comment]
@tiendan is it normal that I can't specify left, right or center for the header after merging your changes? Maybe I did something wrong but I have an error with: `\makecvheader[L]`. `\makecvheader` works though

**Comment by tiendan** [comment]
Hi @timozattol, I believe some things changed after I submitted my PR. Here is the awesome-cv.cls from when I worked on this:
https://github.com/tiendan/Awesome-CV/blob/0d9688fa2c21d7aba5983e12a95ebfba1d6ff2af/awesome-cv.cls#L408

And here is the new version:
https://github.com/posquit0/Awesome-CV/blob/master/awesome-cv.cls#L403

You can see that in the new version the makecvheader command accepts some parameters, whereas the old one doesn't have any. I guess you have to do a manual merge :)

Cheers,
Onur

**Comment by timozattol** [comment]
Alright, thanks @tiendan! :)

**Comment by catesandrew** [comment]
You could replace the top diff with

```latex
\twocolumn[\par{
  \makecvheader[C]

  \makecvfooter
    {\today}
    {}
    {\thepage}
  }]
```

The `@twocolumnfalse` were not required. then I decided to replace that with the following:

```latex
\cvheaderfooter{C}{Claud D. Park~~~·~~~Résumé}
```

Because I wanted to support both one and two column layout with same `cls`. So in `awesome-cv.cls`, add the following after all the `RequirePackage`:

```latex
\newif\ifhbtwocolumn
\@ifclasswith{awesome-cv}{twocolumn}{\hbtwocolumntrue}{\hbtwocolumnfalse}

% Define an entry of cv information
% Usage: \cventry{<position>}{<title>}
\newcommand\cvheaderfooter[2]{%
  \ifhbtwocolumn
    \twocolumn[\par{
    % Print the header with above personal informations
    % Give optional argument to change alignment(C: center, L: left, R: right)
    \makecvheader[#1]
    % Print the footer with 3 arguments(<left>, <center>, <right>)
    % Leave any of these blank if they are not needed
    \makecvfooter
      {\today}
      {#2}
      {\thepage}
    }]
  \else
    \makecvheader[#1]
    \makecvfooter
    {\today}
    {#2}
    {\thepage}
    \fi%
}

\newcommand\cvcolwidth{%
  \ifhbtwocolumn \columnwidth\else \textwidth\fi}
```

We are creating two new commands. The former is the definition for the unified header and footer in the resume. The latter is a command to return either `\columnwidth` or `\textwidth`. We use that command in the definitions of `tabular` now. This is what all the `tabulars` in this diff should now look like:

```latex
\begin{tabular*}{\cvcolwidth}{@{\extracolsep{\fill}} L{\cvcolwidth - 4.5cm} R{4.5cm}}
```

**Comment by jkarimi91** [comment]
any updates on this PR i.e. why was it never merged? A two column layout is a great idea!

**Comment by jkarimi91** [comment]
This is not working for me; my text does not seem to reflow to fit within the boundaries of the columns. Any suggestions?

image

**Comment by tiendan** [comment]
@jkarimi91, are you using **columnwidth** instead of **textwidth**?

**Comment by Terrabdel** [comment]
Hi,
Can you tell me please how to switch to the two column version ?

Thanks,

**Comment by tiendan** [comment]
Hey! I've got my fork of this repo here: https://github.com/tiendan/Awesome-CV

**Comment by tiendan** [comment]
Closing this issue due to inactivity.

**Pull request closed without merging**
