### PR TITLE
Document using Docker to build

### PR DESCRIPTION
**Pull request by rbroggi**
Hi @posquit0 , first of all thank you for the amazing work here. Just wanted to contribute somehow to the repo and something I find myself doing regularly in order to avoid installing packages in my PC is to have docker containers dedicated to the build environment. Specially because my root partition is pretty small compared to my home folder one. Any way, this is a small PR that other users might find usefull.
Thanks once again.

Rodrigo

### CODE REVIEW

**Comment by ThabetAmer** [comment]
I use thomasweise image for pdf generation, with no need to rebuild the container, via command:
docker run -i -w "/doc" -v "$PWD":/doc thomasweise/texlive make

**Comment by OJFord** [comment]
Hi @rbroggi, I like this suggestion - could we use the Docker image used in CI though, just for consistency (the one mentioned above by ThabetAmer I believe)?

**Comment by rbroggi** [comment]
absolutely, will correct it :)

**Comment by rbroggi** [comment]
> Hi @rbroggi, I like this suggestion - could we use the Docker image used in CI though, just for consistency (the one mentioned above by ThabetAmer I believe)?

Done as requested @OJFord . Notice that I also included the `--user $(id -u):$(id -g)` flag in order to preserve the user permissions of the user executing the command

**Comment by OJFord** [comment]
Great, many thanks!

**Pull request closed without merging**
