### PR TITLE
Add note for symbolic links on Windows

### PR DESCRIPTION
**Pull request by oleksis**

### CODE REVIEW

**Comment by OJFord** [comment]
Hi, thanks, I assume this is in relation to #21 - does this actually fix the problem though?

> core.symlinks
>    If false, symbolic links are checked out as small plain files that contain the link text. git-update-index[1] and git-add[1] will not change the recorded type to regular file. Useful on filesystems like FAT that do not support symbolic links.
>
>    The default is true, except git-clone[1] or git-init[1] will probe and set core.symlinks false if appropriate when the repository is created.

I don't think setting this to true (*after* cloning? Otherwise it would just be overridden?) is going to make symlinks magically work on Windows?

I'm inclined not to address this at all, since it's just a general gotcha to be aware of for git users on Windows, not something Awesome-CV specific.

The 'How to use' section in the readme already suggests a docker image (where the symlink should work fine) and the non-docker option says nothing about the examples, just referencing an hypothetical 'your-cv.tex'; there's really no need for a Windows _user_ (using Awesome-CV for their own CV) to use git or symlinks.

(Developing Awesome-CV from Windows is another matter, but that's where IMO 'you're a git user and a Windows user, you figure it out' comes in. Some suggestions here: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows)

**Comment by oleksis** [comment]
> I don't think setting this to true (*after* cloning? Otherwise it would just be overridden?) is going to make symlinks magically work on Windows?

My recommendation is add the note for Windows user set the configuration before clone the repository 


> The 'How to use' section in the readme already suggests a docker image (where the symlink should work fine) and the non-docker option says nothing about the examples, just referencing an hypothetical 'your-cv.tex'; there's really no need for a Windows _user_ (using Awesome-CV for their own CV) to use git or symlinks.

The Docker option in Windows no work if your clone the repository without symlinks

**Comment by OJFord** [comment]
> My recommendation is add the note for Windows user set the configuration before clone the repository

But it sounds like it will be overridden by `git clone` ("will probe and set core.symlinks false if appropriate") and even if not does it work anyway?

> The Docker option in Windows no work if your clone the repository without symlinks

It should if you clone inside the container.

**Comment by oleksis** [comment]
> But it sounds like it will be overridden by `git clone` ("will probe and set core.symlinks false if appropriate") and even if not does it work anyway?

Before cloning the repository, the git configuration can be read on a per-user basis if you use `--global` therefore git-clone could reproduce symbolic links (hardlinks + junctions) on Windows. Then when you use Docker from Windows mapping the source directory you could generate the PDFs without problems

**Comment by dcsim** [comment]
While a reduction of the LaTeX specific questions or system configuration specific questions that pop up in issues might not be a bad thing, it would require an encyclopedic readme. 

I can't comment on whether this actually fixes the problem or not, but I think this specific advice in the readme is not necessary because:

> it's just a general gotcha to be aware of for git users on Windows, not something Awesome-CV specific.

This doesn't mean people haven't asked and had the question answered before, see #21.

Similarly, information about underling or italicizing particular words wouldn't go in the readme for a similar reason: it is a general thing about LaTeX to be aware of not something specific to Awesome-CV. That doesn't mean people haven't asked, see #347. A disclaimer that `tabular*` doesn't break across pages isn't necessary in the readme: it is a general thing about LaTeX to be aware of not something specific Awesome-CV. That doesn't mean that people haven't asked, see #288, #331, and #341.

The issues referenced above are for illustrative purposes only. I appreciate the many people who have contributed helpful answers about LaTeX in response to questions posed and hope the approachable nature of Awesome-CVs Issues page has encouraged people to continue learning and using LaTeX.

**Pull request closed without merging**
