### PR TITLE
Fix errors related to fonts

### PR DESCRIPTION
**Pull request by aminmkhan**
- Fixes error: `! LaTeX3 Error: Command '\FA' already defined!` (posquit0, issue #234)
- Fixes error: `font not found` (posquit0, PR #98)

### CODE REVIEW

**Comment by aminmkhan** [comment]
@posquit0 Tested on macOS. The fix has already been proposed and mentioned in other issues and PRs.

- @AntoniniP #98 
- @ashwinvis #234 / aminmkhan/Awesome-CV#6

**Comment by maxammann** [comment]
Fixes my problems on Arch Linux. Would love to see this merged.

**Comment by OJFord** [comment]
Thank you - I think many of us have made this or similar fixes over the years as posquit0's had other priorities. I have push access now to help maintain Awesome-CV; so I went with my old PR for this (#235/#344) for no reason other than my own familiarity, that I know it's been working for me.

Please do ping me/open another PR if something's still not right or I missed something though! Cheers.

**Comment by aminmkhan** [comment]
Thanks a lot @OJFord, that's good update, and timely now for me to clean-up my #23 ...

**Pull request closed without merging**
