### PR TITLE
Support for photo ID

### PR DESCRIPTION
**Pull request by nitrogl**
Hi,

I've just added some support for photo ID following the way you use to write your latex code.
I transparently included in the \makeheader, hopefully in the right way.

The user is only supposed to (optionally) use the command \photoid.

% Usage: \photoid[circle|rectangle]{<path-to-image>}
\newcommand{\photoid}[2][circle]{\def\@phidedge{#1}\def\@phid{#2}}

Hoping this may help.
Cheers,
Roberto

### CODE REVIEW

**Comment by xgenvn** [comment]
+1

**Comment by nitrogl** [comment]
Additionally, I've added support for a gradient effect in the highlight section

**Comment by Cruel** [comment]
Works great. I didn't care much for the red photo border and I removed it, but other than that I'm definitely going to use this. 👍

**Comment by nitrogl** [comment]
Thanks Cruel for your feedback!
I've added support for "noedge" with examples in tex files; the edge colour, if present, is the same as the theme colour, not necessarily red.

**Comment by Masshat** [comment]
Hi Guys I guess that the owner of this repository is not checking this pull request any more, I think it is better if you continue the dev in your forked repo!

**Comment by posquit0** [comment]
I'll check this PR and merge to origin in a few days. Sorry to late response :(

**Comment by nitrogl** [comment]
Sure, thanks. I tried to follow the style you used to use as much as I could; please feel free to commit changes as well ;)

**Comment by posquit0** [comment]
Merged.
Thanks to your great implementation for profile photo.
I decided to rename 'photoid' to 'photo', to modify an effect of 'edge' mode and to remove gradient section color.
I added optional options('left|right') for 'photo' command to set the position of photo. In addition, `\makecvheader` command has a new options to align as well. (L: left, R: right, C: center)

**Pull request merged**
