### PR TITLE
Fix #234: redefinition of \FA, upgrade to fontawesome5

### LINKED ISSUE #234: Error: Command \FA already defined
https://github.com/posquit0/Awesome-CV/blob/master/awesome-cv.cls#L164 causes:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/command-already-defined"
!
! Command '\FA' already defined!
!
! See the LaTeX3 documentation for further information.
!
! For immediate help type H <return>.
!...............................................
```

due to a change in `fontspec` as described in: https://tex.stackexchange.com/a/453198/73121.

### PR DESCRIPTION
**Pull request by OJFord**
My previous PR #235 was closed as 'invalid duplicate bug', which I'm not quite sure what means, and this seems to remain unfixed to a lot of people including me.

I tried master again, but still had the issue; rebased my changes, and it still fixes it. (Tested Linux & macOS.)

If this fix is 'invalid' for some reason, or it should work as-is I'm just doing something wrong, please, let me know - I'd love to be using `awesome-cv` properly so that I don't have to maintain my fork, or if _a_ fix is needed just not this one, I can try to improve it.

Thanks.

### CODE REVIEW

**Comment by vpatel9202** [comment]
I wish I had checked PRs before spending hours trying to figure out why I couldn't compile the PDFs. Anyway, I approached the same issue you're talking about in a [different way](https://github.com/posquit0/Awesome-CV/pull/345) so it's definitely a problem that exists and has not been addressed.

It may be useful for you to merge my approach with yours so that Github Actions auto generates PDFs on each new push, saving you the trouble of having to have the TeX environment set up locally.

**Comment by OJFord** [comment]
@vpatel9202 I'm not sure that relates to this issue, what is there to render from awesome-cv itself?

Funnily enough though my own CV is also GitHub Action, and formerly Circle CI, rendered/released. I have an auto-updating texlive image at OJFord/docker-texlive for the purpose too, in case that's of any help.

I don't think this PR needs anything to do with how it's rendered though, this is just fixing an error that occurs however (so far as I can tell) the rendering is done.

**Comment by vpatel9202** [comment]
The way I solved the font issue was to install the font package into the docker container that does the rendering (which, admittedly seems like a roundabout way to do it comparing to how you remedied the situation). So we're having the same issue with TeX throwing errors when it can't finding FontAwesome, but we solved it in different ways. I think your approach is more direct and solves problem with Awesome-CV itself while I was utilizing a docker to get around the problem.

**Comment by dcsim** [comment]
Should the symlink to `fontawesome.sty` in `examples/` removed as well? I can't see what purpose it's serving after this merge but it's possible I'm missing something.

**Comment by OJFord** [comment]
Quite possibly @dcsim, I'll check later (writing from phone). Thanks for all your help in issues recently by the way!

**Comment by OJFord** [comment]
Oh yes, for sure. Thanks!

**Pull request merged**
