### PR TITLE
Add telegram

### PR DESCRIPTION
**Pull request by a-morelos**
Add `\telegram` command to show writer's Telegram nickname

### CODE REVIEW

**Comment by OJFord** [comment]
Thanks! Is there something that could be meaningfully hyperlinked? I don't know if Telegram provides URLs that go directly to DM the user for example?

**Comment by a-morelos** [comment]
Yes, in fact exists the t.me shortlink, it should work as https://t.me/<username>

**Comment by OJFord** [comment]
👍🏻 If you could add that as `\href{ }` for consistency with the others, I'd be happy to merge.

**Comment by a-morelos** [comment]
Added `\href{ }` reference for Telegram

**Review by OJFord — APPROVED** [review]

**Pull request closed without merging**
