### PR TITLE
Added stackoverflow, makefile for testing changes.

### PR DESCRIPTION
**Pull request by androm3da**

### CODE REVIEW

**Comment by posquit0** [comment]
Sorry for late :)

**Comment by posquit0** [comment]
I found a error during CI.
--------
! LaTeX Error: File `unicode-math.sty' not found.
--------
I know `unicode-math.sty` is included in `texlive-math-extra`. And it is included in `texlive-full` package. The system of Travis-CI successfully installed this package, I checked a log. I don't know why this error was happened.

**Comment by androm3da** [comment]
There's an [outstanding issue for Travis to support `texlive`](https://github.com/travis-ci/travis-ci/issues/1235).  But it's unresolved and doesn't look like it will make progress.

The approach that they use here is interesting: https://github.com/cdlm/github-travis-latex/blob/master/.travis.yml -- but I think it wouldn't include `unicode-math` and other dependencies since it's so small.

**Comment by androm3da** [comment]
I can revert the `.travis.yml` commit and that will leave the `Makefile` with the test target.

**Comment by posquit0** [comment]
I removed `.travis.yml`, thanks!

**Pull request merged**
