### PR TITLE
Updated to use Font Awesome 5

### PR DESCRIPTION
**Pull request by derekprovance**
This project doesn't compile at all on mac due to the font libraries being a bit different. I did some research and realized it could be remedied by simply upgrading the package to fontawesome5.

### CODE REVIEW

**Comment by schra** [comment]
Can confirm that this works great. Thanks for sharing!

**Comment by Lucretia** [comment]
I cannot build the main repo, but I can build this.

**Comment by Frank5000** [comment]
Does this require you to install fontawesome5 system-wide?

**Review by laeberkaes — APPROVED** [review]

**Comment by OJFord** [comment]
Thank you - I think many of us have made this fix over the years as posquit0's had other priorities. I have push access now to help maintain Awesome-CV; so I went with my old PR for this (#235/344) for no reason other than my own familiarity, that I know it's been working for me.

Please do ping me/open another PR if something's still not right or I missed something though! Cheers.

**Pull request closed without merging**
