### PR TITLE
"The font "FontAwesome" cannot be found."

### PR DESCRIPTION
**Pull request by voncay**
Hello,  

- Add an alternative shortcut to load the Font Awesome font in the fontawesome.sty file to fix the font error path on my system (macOS 10.10.5 with a full texlive 2016 setup) in case anyone else has encountered this error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "FontAwesome" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................
```
- Add an __known error__ topic to help users identify and fix errors  

Hope it'll help.
Thank you for this template.

### CODE REVIEW

**Comment by posquit0** [comment]
Try again with latest source code! I fixed this issue few days ago.

**Comment by voncay** [comment]
I just tried with a fresh git clone but the issue remains on my system (OSX Yosemite + full TeX Live 2016).

**Comment by DaxChen** [comment]
Do you have the font `FontAwesome` **on your mac**?
Download the `.otf` and double click on it will install it. You can find it [here](https://github.com/plorcupine/latex-fontawesome#requirements)

**Comment by abhilash1in** [comment]
Having the same problem! `FontAwesome` is present in the `fonts/` directory but for some reason, `xelatex` is not able to to find the font.

**Comment by nelsonmestevao** [comment]
@abhilash1in try to install the font also. Like open `fonts/` and install the `.ttf` file.

**Comment by OJFord** [comment]
Thank you - I think many of us have made this or similar fixes over the years as posquit0's had other priorities. I have push access now to help maintain Awesome-CV; so I went with my old PR for this (#235/#344) for no reason other than my own familiarity, that I know it's been working for me.

Please do ping me/open another PR if something's still not right or I missed something though! Cheers.

**Pull request closed without merging**
