### PR TITLE
Add 'publication' section and its style

### PR DESCRIPTION
**Pull request by jonghoonseo**
For several researchers, 'Publication' section is necessary in the curriculum vitae.
So, I added the section and its style.
Please review the modified cv.pdf file.

### CODE REVIEW

**Comment by jonghoonseo** [comment]
As you know, the conflicted file is just an example binary file.
It can be resolved to merge mine.

**Comment by johannesbottcher** [comment]
It doesn't make sense, imho, to add yet another fixed defintion that will lead to several *i want the publication list differently*.

**Comment by jonghoonseo** [comment]
Ummm... yeah it seems little bit make sense. However, I think, espeically in the CV format, publication section is very popular and it is not covered by the conventional definition.If you think there is any way to make 'publication' section by the conventional definition, then please kindly recommend me to replace this new definition. Otherwise, I think this still useful.


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------보낸 사람: Johannes Böttcher <notifications@github.com> 날짜: 17/10/29  오후 10:14  (GMT+09:00) 받은 사람: posquit0/Awesome-CV <Awesome-CV@noreply.github.com> 참조: jonghoonseo <jonghoon.seo@gmail.com>, Author <author@noreply.github.com> 제목: Re: [posquit0/Awesome-CV] Add 'publication' section and its style (#152) 
It doesn't make sense, imho, to add yet another fixed defintion that will lead to several i want the publication list differently.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/posquit0/Awesome-CV","title":"posquit0/Awesome-CV","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/posquit0/Awesome-CV"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johannesbottcher in #152: It doesn't make sense, imho, to add yet another fixed defintion that will lead to several *i want the publication list differently*."}],"action":{"name":"View Pull Request","url":"https://github.com/posquit0/Awesome-CV/pull/152#issuecomment-340261566"}}}

**Comment by johannesbottcher** [comment]
The wikibook shows [two different Publications sections for CVs](https://en.wikibooks.org/wiki/LaTeX/Curriculum_Vitae#A_customizable_Layout) just as an example. Using BibTeX would also be possible. 

There is no right or wrong way to do such a list and depends completely on personal liking.

**Comment by jonghoonseo** [comment]
Oh, thanks for guide. I'll check it deeply.


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------보낸 사람: Johannes Böttcher <notifications@github.com> 날짜: 17/10/29  오후 11:11  (GMT+09:00) 받은 사람: posquit0/Awesome-CV <Awesome-CV@noreply.github.com> 참조: jonghoonseo <jonghoon.seo@gmail.com>, Author <author@noreply.github.com> 제목: Re: [posquit0/Awesome-CV] Add 'publication' section and its style (#152) 
The wikibook shows two different Publications sections for CVs just as an example. Using BibTeX would also be possible.
There is no right or wrong way to do such a list and depends completely on personal liking.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/posquit0/Awesome-CV","title":"posquit0/Awesome-CV","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/posquit0/Awesome-CV"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johannesbottcher in #152: The wikibook shows [two different Publications sections for CVs](https://en.wikibooks.org/wiki/LaTeX/Curriculum_Vitae#A_customizable_Layout) just as an example. Using BibTeX would also be possible. \r\n\r\nThere is no right or wrong way to do such a list and depends completely on personal liking. "}],"action":{"name":"View Pull Request","url":"https://github.com/posquit0/Awesome-CV/pull/152#issuecomment-340265225"}}}

**Comment by aminmkhan** [comment]
Related to #23.

**Pull request closed without merging**
