### PR TITLE
VS Code integration

### PR DESCRIPTION
**Pull request by gnikit**
Not sure if this is within the scope of this repo, so feel free to close if not. 

VSCode users, especially those who have enabled the option "compile on document save", have to manually compile and/or ignore the compilation errors from latexmk.

The errors are due to latexmk using pdflatex by default. This PR sets the default build command for vscode to the predefined build option `latexmk (lualatex)`, making this repo work out of the gate with vscode.

## Additional notes

The recommended exntesion is [this](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop), which is the most popular and widely used LaTex extension in VSCode by a long shot.

### CODE REVIEW

**Comment by OJFord** [comment]
My feeling is that this encourages using this repo directly for one's own CV, rather than importing the `.cls` into a distinct one.

That results in a lot of PRs with the examples changed to someone's real information, which is just noise and not a helpful diff. (It's fine to add examples of new features to them of course - but there's no point changing a name, or the year, or a company etc., that will never make sense, it's just an example.)

I've been thinking about having a 'template repo' (a GitHub feature) to help discourage that - a blank slate rather than an example, except for including AwesomeCV correctly and rendering in an Action etc. This would be a good fit there.

**Comment by gnikit** [comment]
> My feeling is that this encourages using this repo directly for one's own CV, rather than importing the `.cls` into a distinct one.
> 
> That results in a lot of PRs with the examples changed to someone's real information, which is just noise and not a helpful diff. (It's fine to add examples of new features to them of course - but there's no point changing a name, or the year, or a company etc., that will never make sense, it's just an example.)

I would hope that GitHub users are smart enough to know when they should be opening PRs, but as you said this is a potential *can of snakes* situation.


> I've been thinking about having a 'template repo' (a GitHub feature) to help discourage that - a blank slate rather than an example, except for including AwesomeCV correctly and rendering in an Action etc. This would be a good fit there.

That sounds like a very good idea, making a template repo with the .cls + build instructions and then either a link to a repo with examples or having the examples as a git submodule would simplify things a lot.

Let me know if you choose to go down this path and want some help!

**Comment by gnikit** [comment]
Feel free to close this PR anytime

**Comment by tgeorg-ethz** [comment]
> My feeling is that this encourages using this repo directly for one's own CV, rather than importing the `.cls` into a distinct one.

In that case a quick alternative to this PR would be to then mention the necessary steps for local compilation using vscode and latex-workshop in the README.

**Comment by OJFord** [comment]
I don't use VSCode and have never heard of latex-workshop, it's way out of scope to explain how to use specific tools in this project's readme.

Still vaguely intending to do the template thing, just haven't gotten around to it.

**Pull request closed without merging**
