### PR TITLE
Add `\kaggle` command

### PR DESCRIPTION
**Pull request by awsaf49**
[Kaggle](https://www.kaggle.com) is a popular platform for Data  Science & Machine Learning. This PR is meant to add `\kaggle` command so that we can add **kaggle** in our **cv/resume**. 
Even though it works, it doesn't show any `icons`. As mentioned, in #379, this issue might get solved by some help.

### CODE REVIEW

**Comment by awsaf49** [comment]
@OJFord Could you please have a look?

**Comment by OJFord** [comment]
Thanks @awsaf49 I'll try it. So other icons _are_ working for you, just not the Kaggle one?

**Comment by awsaf49** [comment]
> Thanks @awsaf49 I'll try it. So other icons _are_ working for you, just not the Kaggle one?

Yes, btw how can we know if `faKaggle` has any icon or not?

**Comment by dcsim** [comment]
> > Thanks @awsaf49 I'll try it. So other icons _are_ working for you, just not the Kaggle one?
> 
> Yes, btw how can we know if `faKaggle` has any icon or not?

Kaggle is faKaggle.

Adding your definition for kaggle and `ifthenthensle` for kaggle work as expected in a fresh clone.

image

**Comment by awsaf49** [comment]
> > > Thanks @awsaf49 I'll try it. So other icons _are_ working for you, just not the Kaggle one?
> > 
> > 
> > Yes, btw how can we know if `faKaggle` has any icon or not?
> 
> Kaggle is faKaggle.
> 
> Adding your definition for kaggle and `ifthenthensle` for kaggle work as expected in a fresh clone.
> 
> image

I think then it was some mistake from my end. @OJFord you can merge the PR if you want as it's working.

**Review by OJFord — APPROVED** [review]

**Comment by OJFord** [comment]
Bah, intended to link in and close via db809982227ba6f24f2d0ec1c4f3893e99db2f41.

**Pull request closed without merging**
