### PR TITLE
Update fontawesome.sty

### PR DESCRIPTION
**Pull request by AntoniniP**
Edited path to FontAwesome folder, otherwise it would go unrecognised (fontspec error: "font-not-found").

### CODE REVIEW

**Comment by Puriney** [comment]
the missing font error went away. thanks a lot ;-)

P.S. the missfont.log has records like: `mktextfm FontAwesome`.

**Comment by nikhilweee** [comment]
I had the same problem. This solution worked for me too!

**Comment by mic4ael** [comment]
Why hasn't this been merged so far? This is a thing that fixes apparently a common problem.

**Comment by aminmkhan** [comment]
@AntoniniP Also include this fix [here](https://github.com/aminmkhan/Awesome-CV/commit/97c094f2c469b42affe8bee7b8db0db7b782ba8a) in `awesome-cv.cls`.

```
\setfontfamily\FA[Path=\@fontdir]{FontAwesome}
```

**Comment by aminmkhan** [comment]
Also proposed the same fix to @posquit0 in #291.

**Comment by ndPPPhz** [comment]
I agree with @aminmkhan. This does seem to solve the issue regarding the `The font "FontAwesome" cannot be found.` error message which could not be found on the root folder. I had to either add the Path tag manually or move the font in to the root folder.

**Comment by OJFord** [comment]
Thank you - I think many of us have made this or similar fixes over the years as posquit0's had other priorities. I have push access now to help maintain Awesome-CV; so I went with my old PR for this (#235/#344) for no reason other than my own familiarity, that I know it's been working for me.

Please do ping me/open another PR if something's still not right or I missed something though! Cheers.

**Comment by aminmkhan** [comment]
Thanks a lot @OJFord, it's great to have a new maintainer! 💪

**Pull request closed without merging**
